labels_map = {'raaga':  {'Abheri / Bhimpalas': 0,
                         'Bageshri': 1,
                         'Brindavan Sarang': 2,
                         'Chakravakam / Ahir Bhairav': 3,
                         'Charukeshi': 4,
                         'Darbari': 5,
                         'Desh': 6,
                         'Gavati': 7,
                         'Gowri Manohari / Patdeep': 8,
                         'Hamsadhwani': 9,
                         'Hamsanandi / Sohini': 10,
                         'Harikamboji': 11,
                         'Hindolam / Malkauns': 12,
                         'Jaunpuri': 13,
                         'Kalyani / Yaman': 14,
                         'Keeravani': 15,
                         'Maand': 16,
                         'Madhyamavati / Madhmad Sarang': 17,
                         'Mayamalavagowla / Bhairav': 18,
                         'Mohanam / Bhoop': 19,
                         'Natabhairavi': 20,
                         'Pahadi': 21,
                         'Pantuvarali / Puriya Dhanashri': 22,
                         'Pilu': 23,
                         'Shankarabharanam / Bilawal': 24,
                         'Shivaranjani': 25,
                         'Shubha Pantuvarali / Miyan ki Todi': 26,
                         'Shuddha Dhanyasi': 27,
                         'Sindhu Bhairavi / Bhairavi': 28,
                         'Tilang': 29,
                         'Vakulabharanam': 30,
                         'Yaman Kalyan': 31}
             }

CRAWLER_SETTINGS = {
    'feed_uri': 'data/raw/bhajans_info.json',
    'feed_format': 'json',
}

RAAGA_COUNT_THRESH = 10